Repository dnd-side-project/dnd-10th-10-backend, pull requests merged in 2024-01, with the labels that each got.

#2 🔧chore: 프로젝트 세팅
  .github/CODEOWNERS
  .github/pull_request_template.md
  .gitignore
  basterdz-api/build.gradle
  basterdz-api/src/main/java/com/dnd/BasterdzApiApplication.java
  basterdz-api/src/main/resources/banner.txt
  basterdz-common/build.gradle
  basterdz-domain/build.gradle
  basterdz-infra/build.gradle
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
Labels: 🔧 Config

#4 🔧chore: jacoco 설정
  .github/CODEOWNERS
  .github/workflows/ci.yml
  build.gradle
Labels: 🔧 Config

#6 🔧chore: Logback 설정
  basterdz-api/src/main/resources/console-appender.xml
  basterdz-api/src/main/resources/file-info-appender.xml
  basterdz-api/src/main/resources/logback-spring.xml
Labels: 🔧 Config

#7 📝docs: issue template 생성
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: 📝Docs

#12 ✨feature: 기본 Entity 생성
  basterdz-domain/build.gradle
  basterdz-domain/src/main/java/com/dnd/BasterdzDomainApplication.java
  basterdz-domain/src/main/java/com/dnd/common/entity/BaseTimeEntity.java
  basterdz-domain/src/main/java/com/dnd/member/Member.java
  basterdz-domain/src/main/java/com/dnd/notice/Booster.java
  basterdz-domain/src/main/java/com/dnd/report/DailyReport.java
  basterdz-domain/src/main/java/com/dnd/report/RankingReport.java
  basterdz-domain/src/main/java/com/dnd/room/Room.java
  basterdz-domain/src/main/java/com/dnd/room/RoomMember.java
  basterdz-domain/src/main/java/com/dnd/room/vo/RestrictApp.java
Labels: ✨Feature
