Repository dnd-side-project/dnd-10th-10-backend, pull requests merged in 2024-02, with the labels that each got.

#13 ✨feature: 전역 에러 핸들링
  basterdz-api/build.gradle
  basterdz-api/src/main/java/com/dnd/common/ErrorCode.java
  basterdz-api/src/main/java/com/dnd/common/GlobalExceptionHandler.java
  basterdz-api/src/main/java/com/dnd/common/SampleController.java
  basterdz-api/src/main/java/com/dnd/common/SampleRequestDto.java
  basterdz-api/src/main/java/com/dnd/common/SampleResponseDto.java
  basterdz-api/src/main/java/com/dnd/common/dto/ApiError.java
  basterdz-api/src/main/java/com/dnd/common/dto/ApiResult.java
  basterdz-api/src/main/java/com/dnd/common/error/BasterdzException.java
  basterdz-api/src/main/java/com/dnd/common/error/NotFoundException.java
  basterdz-api/src/main/java/com/dnd/common/error/UnauthorizedException.java
Labels: ✨Feature

#17 ♻️ refactor: 에러 핸들링 리팩토링 및 에러코드 추가
  basterdz-api/src/main/java/com/dnd/common/ErrorCode.java
  basterdz-api/src/main/java/com/dnd/common/GlobalExceptionHandler.java
  basterdz-api/src/main/java/com/dnd/common/SampleController.java
  basterdz-api/src/main/java/com/dnd/common/SampleRequestDto.java
  basterdz-api/src/main/java/com/dnd/common/dto/ApiError.java
  basterdz-api/src/main/java/com/dnd/common/dto/ApiResult.java
  basterdz-api/src/main/java/com/dnd/common/error/BasterdzException.java
  basterdz-api/src/main/resources/application.yml
  basterdz-domain/src/main/resources/db-local.yml
Labels: :recycle: Refactor

#19 :wrench: chore: mysql docker compose 파일 추가
  docker/basterdz-container/docker-compose.local.yml
Labels: 🔧 Config

#20 ✨ feature: 방 생성 기능 추가
  basterdz-api/build.gradle
  basterdz-api/src/main/java/com/dnd/domains/room/controller/RoomController.java
  basterdz-api/src/main/java/com/dnd/domains/room/dto/request/RoomCreateRequestDto.java
  basterdz-api/src/main/java/com/dnd/domains/room/dto/response/RoomCreateResponseDto.java
  basterdz-api/src/main/java/com/dnd/domains/room/service/RoomService.java
  basterdz-domain/src/main/java/com/dnd/common/entity/BaseTimeEntity.java
  basterdz-domain/src/main/java/com/dnd/room/Room.java
  basterdz-domain/src/main/java/com/dnd/room/RoomRepository.java
Labels: ✨Feature

#24 ✨ feature: Swagger 설정
  basterdz-api/build.gradle
  basterdz-api/src/main/java/com/dnd/common/SampleController.java
  basterdz-api/src/main/java/com/dnd/common/SampleRequestDto.java
  basterdz-api/src/main/java/com/dnd/common/SampleResponseDto.java
  basterdz-api/src/main/java/com/dnd/common/config/SwaggerConfigure.java
  basterdz-api/src/main/java/com/dnd/common/dto/ApiError.java
  basterdz-api/src/main/java/com/dnd/common/dto/ApiResult.java
  basterdz-api/src/main/java/com/dnd/common/error/ErrorCode.java
  basterdz-api/src/main/java/com/dnd/common/error/GlobalExceptionHandler.java
  basterdz-api/src/main/java/com/dnd/common/error/exception/BasterdzException.java
  basterdz-api/src/main/java/com/dnd/common/error/exception/NotFoundException.java
  basterdz-api/src/main/java/com/dnd/common/error/exception/UnauthorizedException.java
  basterdz-api/src/main/java/com/dnd/domains/room/controller/RoomApiPresentation.java
  basterdz-api/src/main/java/com/dnd/domains/room/controller/RoomController.java
  basterdz-api/src/main/java/com/dnd/domains/room/dto/request/RoomCreateRequestDto.java
  basterdz-api/src/main/java/com/dnd/domains/room/dto/response/RoomCreateResponseDto.java
  basterdz-api/src/main/resources/application.yml
Labels: ✨Feature

#22 ✅ test: 방 생성에 대한 테스트 코드 작성
  basterdz-api/src/main/java/com/dnd/domains/room/dto/request/RoomCreateRequestDto.java
  basterdz-api/src/main/java/com/dnd/domains/room/service/RoomService.java
  basterdz-api/src/main/java/com/dnd/domains/room/util/InviteCodeGenerator.java
  basterdz-api/src/main/java/com/dnd/domains/room/util/InviteCodeUtil.java
  basterdz-api/src/main/resources/application.yml
  basterdz-api/src/test/java/com/dnd/BasterdzApiApplicationTests.java
  basterdz-api/src/test/java/com/dnd/domains/room/service/RoomServiceTest.java
  basterdz-domain/build.gradle
  basterdz-domain/src/main/java/com/dnd/BasterdzDomainApplication.java
  basterdz-domain/src/main/resources/db-local.yml
  basterdz-domain/src/main/resources/db-test.yml
Labels: ✅ Test

#26 ✨ feature: 방 조회 기능 추가
  basterdz-api/src/main/java/com/dnd/domains/room/controller/RoomApiPresentation.java
  basterdz-api/src/main/java/com/dnd/domains/room/controller/RoomController.java
  basterdz-api/src/main/java/com/dnd/domains/room/dto/request/CreateRoomRequestDto.java
  basterdz-api/src/main/java/com/dnd/domains/room/dto/response/CreateRoomResponseDto.java
  basterdz-api/src/main/java/com/dnd/domains/room/dto/response/FindRoomByCodeResponseDto.java
  basterdz-api/src/main/java/com/dnd/domains/room/dto/response/FindRoomResponseDto.java
  basterdz-api/src/main/java/com/dnd/domains/room/service/RoomService.java
  basterdz-api/src/test/java/com/dnd/domains/room/service/RoomServiceTest.java
  basterdz-domain/src/main/java/com/dnd/room/Room.java
  basterdz-domain/src/main/java/com/dnd/room/RoomRepository.java
Labels: ✨Feature

#29 :sparkles: feat: 인증 ArgumentResolver 구현
  basterdz-api/src/main/java/com/dnd/auth/LoginMember.java
  basterdz-api/src/main/java/com/dnd/auth/LoginMemberArgumentResolver.java
  basterdz-api/src/main/java/com/dnd/common/config/WebMvcConfig.java
  basterdz-api/src/main/java/com/dnd/domains/SampleController.java
  basterdz-domain/src/main/java/com/dnd/member/MemberFinder.java
  basterdz-domain/src/main/java/com/dnd/member/MemberJpaRepository.java
Labels: ✨Feature

#34 ✨ feat: 스크린 타임 업데이트 기능
  basterdz-api/src/main/java/com/dnd/api/common/config/JasyptConfig.java
  basterdz-api/src/main/java/com/dnd/api/domains/report/controller/ScreenReportApiPresentation.java
  basterdz-api/src/main/java/com/dnd/api/domains/report/controller/ScreenReportController.java
  basterdz-api/src/main/java/com/dnd/api/domains/report/dto/ScreenReportRequest.java
  basterdz-api/src/main/java/com/dnd/api/domains/report/service/ScreenReportService.java
  basterdz-api/src/main/java/com/dnd/api/domains/room/dto/request/CreateRoomRequestDto.java
  basterdz-api/src/main/java/com/dnd/api/domains/room/dto/response/FindRoomByCodeResponseDto.java
  basterdz-api/src/main/java/com/dnd/api/domains/room/dto/response/FindRoomResponseDto.java
  basterdz-api/src/test/java/com/dnd/domains/room/service/RoomServiceTest.java
  basterdz-common/src/main/java/com/dnd/common/exception/ErrorCode.java
  basterdz-domain/src/main/java/com/dnd/domain/member/MemberFinder.java
  basterdz-domain/src/main/java/com/dnd/domain/report/DailyReport.java
  basterdz-domain/src/main/java/com/dnd/domain/report/entity/RankingReport.java
  basterdz-domain/src/main/java/com/dnd/domain/report/entity/ScreenReport.java
  basterdz-domain/src/main/java/com/dnd/domain/report/entity/ScreenTime.java
  basterdz-domain/src/main/java/com/dnd/domain/report/implement/ScreenReportAppender.java
  basterdz-domain/src/main/java/com/dnd/domain/report/implement/ScreenReportFinder.java
  basterdz-domain/src/main/java/com/dnd/domain/report/repository/ScreenReportJpaRepository.java
  basterdz-domain/src/main/java/com/dnd/domain/room/entity/RestrictApp.java
  basterdz-domain/src/main/java/com/dnd/domain/room/entity/Room.java
  basterdz-domain/src/main/java/com/dnd/domain/vo/RestrictApp.java
  basterdz-domain/src/main/resources/db-local.yml
Labels: ✨Feature

#36 :wrench: chore: github-workflows 작성
  .github/workflows/cd-dev.yml
  basterdz-api/Dockerfile
  basterdz-api/src/main/resources/application.yml
  basterdz-domain/src/main/resources/db-dev.yml
  docker/basterdz-container/docker-compose.dev.yml
Labels: 🔧 Config

#38 ✨ feature: 방 입장 시 중복 회원인지 체크하는 로직 추가
  basterdz-api/src/main/java/com/dnd/api/auth/LoginMemberArgumentResolver.java
  basterdz-api/src/main/java/com/dnd/api/domains/report/controller/ScreenReportApiPresentation.java
  basterdz-api/src/main/java/com/dnd/api/domains/report/controller/ScreenReportController.java
  basterdz-api/src/main/java/com/dnd/api/domains/report/service/ScreenReportService.java
  basterdz-api/src/main/java/com/dnd/api/domains/room/controller/RoomApiPresentation.java
  basterdz-api/src/main/java/com/dnd/api/domains/room/controller/RoomController.java
  basterdz-api/src/main/java/com/dnd/api/domains/room/dto/CreateRoomRequest.java
  basterdz-api/src/main/java/com/dnd/api/domains/room/dto/EnterRoomRequest.java
  basterdz-api/src/main/java/com/dnd/api/domains/room/dto/FindRoomByCodeResponse.java
  basterdz-api/src/main/java/com/dnd/api/domains/room/dto/FindRoomResponse.java
  basterdz-api/src/main/java/com/dnd/api/domains/room/dto/RoomIdResponse.java
  basterdz-api/src/main/java/com/dnd/api/domains/room/service/RoomService.java
  basterdz-api/src/test/java/com/dnd/domains/room/service/RoomServiceTest.java
  basterdz-common/src/main/java/com/dnd/common/exception/ErrorCode.java
  basterdz-domain/src/main/java/com/dnd/domain/member/entity/Member.java
  basterdz-domain/src/main/java/com/dnd/domain/member/implement/MemberAppender.java
  basterdz-domain/src/main/java/com/dnd/domain/member/implement/MemberFinder.java
  basterdz-domain/src/main/java/com/dnd/domain/member/implement/MemberRemover.java
  basterdz-domain/src/main/java/com/dnd/domain/member/repository/MemberJpaRepository.java
  basterdz-domain/src/main/java/com/dnd/domain/notice/Booster.java
  basterdz-domain/src/main/java/com/dnd/domain/room/entity/Room.java
  basterdz-domain/src/main/java/com/dnd/domain/room/entity/RoomMember.java
  basterdz-domain/src/main/java/com/dnd/domain/room/implement/RoomAppender.java
  basterdz-domain/src/main/java/com/dnd/domain/room/implement/RoomFinder.java
  basterdz-domain/src/main/java/com/dnd/domain/room/implement/RoomMemberAppender.java
  basterdz-domain/src/main/java/com/dnd/domain/room/implement/RoomMemberFinder.java
  basterdz-domain/src/main/java/com/dnd/domain/room/implement/RoomMemberRemover.java
  basterdz-domain/src/main/java/com/dnd/domain/room/implement/RoomRemover.java
  basterdz-domain/src/main/java/com/dnd/domain/room/repository/RoomJpaRepository.java
  basterdz-domain/src/main/java/com/dnd/domain/room/repository/RoomMemberJpaRepository.java
  basterdz-domain/src/main/java/com/dnd/domain/vo/RoomStatus.java
Labels: ✨Feature, :recycle: Refactor

#40 ✨ feature: 방 시작 기능 추가
  basterdz-api/src/main/java/com/dnd/api/domains/room/controller/RoomApiPresentation.java
  basterdz-api/src/main/java/com/dnd/api/domains/room/controller/RoomController.java
  basterdz-api/src/main/java/com/dnd/api/domains/room/dto/CreateRoomRequest.java
  basterdz-api/src/main/java/com/dnd/api/domains/room/service/RoomService.java
  basterdz-api/src/main/resources/logback-spring.xml
  basterdz-domain/src/main/java/com/dnd/domain/room/entity/Room.java
  basterdz-domain/src/main/java/com/dnd/domain/room/entity/RoomMember.java
  basterdz-domain/src/main/java/com/dnd/domain/room/entity/RoomStatus.java
  basterdz-domain/src/main/java/com/dnd/domain/room/implement/RoomMemberFinder.java
  basterdz-domain/src/main/java/com/dnd/domain/room/repository/RoomJpaRepository.java
  basterdz-domain/src/main/java/com/dnd/domain/room/repository/RoomMemberJpaRepository.java
Labels: ✨Feature

#41 ✨ feat: 00시 30분 랭킹 집계 스케줄러 구현
  basterdz-api/src/test/java/com/dnd/domains/room/service/RoomServiceTest.java
  basterdz-batch/build.gradle
  basterdz-batch/src/main/java/com/dnd/batch/RankingBatchScheduler.java
  basterdz-batch/src/main/java/com/dnd/batch/RankingJob.java
  basterdz-batch/src/main/java/com/dnd/batch/config/BatchConfig.java
  basterdz-common/src/main/java/com/dnd/util/LocalDateHolder.java
  basterdz-common/src/main/java/com/dnd/util/SystemLocalDateHolder.java
  basterdz-domain/build.gradle
  basterdz-domain/src/main/java/com/dnd/domain/common/config/QuerydslConfig.java
  basterdz-domain/src/main/java/com/dnd/domain/member/entity/Member.java
  basterdz-domain/src/main/java/com/dnd/domain/ranking/RankingReport.java
  basterdz-domain/src/main/java/com/dnd/domain/report/entity/ScreenReport.java
  basterdz-domain/src/main/java/com/dnd/domain/room/dto/RoomMemberRankingDto.java
  basterdz-domain/src/main/java/com/dnd/domain/room/entity/Room.java
  basterdz-domain/src/main/java/com/dnd/domain/room/implement/RoomFinder.java
  basterdz-domain/src/main/java/com/dnd/domain/room/repository/RoomMemberQueryRepository.java
  build.gradle
  settings.gradle
Labels: 🔧 Config, ✨Feature

#43 ✨ feature: 방과 관련된 명세 추가
  basterdz-api/src/main/java/com/dnd/BasterdzApiApplication.java
  basterdz-api/src/main/java/com/dnd/api/domains/room/controller/RoomApiPresentation.java
  basterdz-api/src/main/java/com/dnd/api/domains/room/controller/RoomController.java
  basterdz-api/src/main/java/com/dnd/api/domains/room/dto/CheckHostResponse.java
  basterdz-api/src/main/java/com/dnd/api/domains/room/dto/CreateRoomRequest.java
  basterdz-api/src/main/java/com/dnd/api/domains/room/dto/FindActiveRoomResponse.java
  basterdz-api/src/main/java/com/dnd/api/domains/room/dto/FindActiveRoomsResponse.java
  basterdz-api/src/main/java/com/dnd/api/domains/room/dto/FindFinishedRoomsResponse.java
  basterdz-api/src/main/java/com/dnd/api/domains/room/dto/FindRoomByCodeResponse.java
  basterdz-api/src/main/java/com/dnd/api/domains/room/dto/FindWaitingRoomResponse.java
  basterdz-api/src/main/java/com/dnd/api/domains/room/dto/RoomIdResponse.java
  basterdz-api/src/main/java/com/dnd/api/domains/room/dto/RoomResponse.java
Labels: 📝Docs, ✨Feature

#48 ✨ feat: 방 멤버의 당일 날짜 스크린 사용시간 조회 기능 구현
  basterdz-api/src/main/java/com/dnd/api/common/random/LocalDateHolder.java
  basterdz-api/src/main/java/com/dnd/api/common/random/SystemLocalDateHolder.java
  basterdz-api/src/main/java/com/dnd/api/domains/room/controller/RoomReportApiPresentation.java
  basterdz-api/src/main/java/com/dnd/api/domains/room/controller/RoomReportController.java
  basterdz-api/src/main/java/com/dnd/api/domains/room/dto/RoomMemberScreenTimeResponse.java
  basterdz-api/src/main/java/com/dnd/api/domains/room/service/RoomReportService.java
  basterdz-batch/src/main/java/com/dnd/batch/RankingJob.java
  basterdz-batch/src/main/java/com/dnd/batch/random/LocalDateHolder.java
  basterdz-batch/src/main/java/com/dnd/batch/random/SystemLocalDateHolder.java
  basterdz-common/src/main/java/com/dnd/common/util/TimeConvertUtils.java
  basterdz-domain/src/main/java/com/dnd/domain/room/dto/RoomMemberDailyScreenTime.java
  basterdz-domain/src/main/java/com/dnd/domain/room/implement/RoomFinder.java
  basterdz-domain/src/main/java/com/dnd/domain/room/implement/RoomReportFinder.java
  basterdz-domain/src/main/java/com/dnd/domain/room/repository/RoomMemberQueryRepository.java
  basterdz-domain/src/main/resources/db-local.yml
  docker/basterdz-container/docker-compose.local.yml
Labels: ✨Feature

#49 ✨ feature: 호스트 확인 기능 추가
  basterdz-api/src/main/java/com/dnd/api/domains/room/controller/RoomApiPresentation.java
  basterdz-api/src/main/java/com/dnd/api/domains/room/controller/RoomController.java
  basterdz-api/src/main/java/com/dnd/api/domains/room/dto/CheckHostResponse.java
  basterdz-api/src/main/java/com/dnd/api/domains/room/service/RoomService.java
  basterdz-common/src/main/java/com/dnd/common/exception/ErrorCode.java
  basterdz-domain/src/main/java/com/dnd/domain/room/implement/RoomFinder.java
  basterdz-domain/src/main/java/com/dnd/domain/room/implement/RoomMemberFinder.java
Labels: ✨Feature, :recycle: Refactor

#51 ✨ feature: 방 삭제 기능 추가
  basterdz-api/src/main/java/com/dnd/api/common/error/GlobalExceptionHandler.java
  basterdz-api/src/main/java/com/dnd/api/domains/room/controller/RoomApiPresentation.java
  basterdz-api/src/main/java/com/dnd/api/domains/room/controller/RoomController.java
  basterdz-api/src/main/java/com/dnd/api/domains/room/dto/RoomIdResponse.java
  basterdz-api/src/main/java/com/dnd/api/domains/room/service/RoomService.java
  basterdz-common/src/main/java/com/dnd/common/exception/ErrorCode.java
  basterdz-domain/src/main/java/com/dnd/domain/room/entity/Room.java
  basterdz-domain/src/main/java/com/dnd/domain/room/implement/RoomRemover.java
Labels: ✨Feature, :recycle: Refactor

#54 ✨ feat: 애플 로그인 기능 구현
  .github/workflows/ci.yml
  basterdz-api/build.gradle
  basterdz-api/src/main/java/com/dnd/api/auth/AuthController.java
  basterdz-api/src/main/java/com/dnd/api/auth/AuthService.java
  basterdz-api/src/main/java/com/dnd/api/auth/JwtTokenProperties.java
  basterdz-api/src/main/java/com/dnd/api/auth/JwtTokenProvider.java
  basterdz-api/src/main/java/com/dnd/api/auth/LoginInterceptor.java
  basterdz-api/src/main/java/com/dnd/api/auth/LoginMemberArgumentResolver.java
  basterdz-api/src/main/java/com/dnd/api/auth/apple/AppleClient.java
  basterdz-api/src/main/java/com/dnd/api/auth/apple/AppleProperties.java
  basterdz-api/src/main/java/com/dnd/api/auth/apple/ApplePublicKey.java
  basterdz-api/src/main/java/com/dnd/api/auth/apple/ApplePublicKeyGenerator.java
  basterdz-api/src/main/java/com/dnd/api/auth/apple/ApplePublicKeys.java
  basterdz-api/src/main/java/com/dnd/api/auth/apple/AppleTokenParser.java
  basterdz-api/src/main/java/com/dnd/api/auth/apple/AppleTokenValidator.java
  basterdz-api/src/main/java/com/dnd/api/auth/dto/AppleLoginReqeust.java
  basterdz-api/src/main/java/com/dnd/api/auth/dto/LoginResponse.java
  basterdz-api/src/main/java/com/dnd/api/common/config/FeignClientConfig.java
  basterdz-api/src/main/java/com/dnd/api/common/config/WebMvcConfig.java
  basterdz-api/src/main/resources/application.yml
  basterdz-api/src/test/java/com/dnd/BasterdzApiApplicationTests.java
  basterdz-api/src/test/java/com/dnd/api/auth/JwtTokenProviderTest.java
  basterdz-api/src/test/java/com/dnd/api/auth/apple/AppleClientTest.java
  basterdz-api/src/test/java/com/dnd/domains/room/service/RoomServiceTest.java
  basterdz-domain/src/main/java/com/dnd/domain/member/entity/Member.java
  basterdz-domain/src/main/java/com/dnd/domain/member/entity/OauthMemberInfo.java
  basterdz-domain/src/main/java/com/dnd/domain/member/implement/MemberAppender.java
  basterdz-domain/src/main/java/com/dnd/domain/member/implement/MemberFinder.java
  basterdz-domain/src/main/java/com/dnd/domain/member/repository/MemberJpaRepository.java
  basterdz-domain/src/main/resources/db-test.yml
Labels: ✨Feature

#55 ✨ feat: 방 랭킹 조회
  basterdz-api/src/main/java/com/dnd/api/domains/report/dto/ScreenReportRequest.java
  basterdz-api/src/main/java/com/dnd/api/domains/report/dto/ScreenTimeRequest.java
  basterdz-api/src/main/java/com/dnd/api/domains/room/controller/RoomReportController.java
  basterdz-api/src/main/java/com/dnd/api/domains/room/dto/RoomMemberRankingResponse.java
  basterdz-api/src/main/java/com/dnd/api/domains/room/service/RoomReportService.java
  basterdz-domain/src/main/java/com/dnd/domain/ranking/RankingReport.java
  basterdz-domain/src/main/java/com/dnd/domain/ranking/RankingReportRepository.java
  basterdz-domain/src/main/java/com/dnd/domain/report/entity/ScreenReport.java
  basterdz-domain/src/main/java/com/dnd/domain/room/dto/RoomMemberDailyScreenTime.java
  basterdz-domain/src/main/java/com/dnd/domain/room/implement/RoomReportFinder.java
Labels: ✨Feature

#57 :bug: hotfix: swagger 문서 오류 수정
  basterdz-api/src/main/java/com/dnd/api/domains/report/controller/ScreenReportApiPresentation.java
  basterdz-api/src/main/java/com/dnd/api/domains/room/controller/RoomApiPresentation.java
  basterdz-api/src/main/java/com/dnd/api/domains/room/controller/RoomReportApiPresentation.java
  basterdz-api/src/main/java/com/dnd/api/domains/room/dto/RoomMemberRankingResponse.java
  basterdz-api/src/main/java/com/dnd/api/domains/room/dto/RoomMemberScreenTimeResponse.java
  basterdz-api/src/test/java/com/dnd/api/auth/JwtTokenProviderTest.java
Labels: 🐛Bug

#60 :recycle: refactor: 엔드포인트 수정
  basterdz-api/src/main/java/com/dnd/api/domains/room/controller/RoomController.java
Labels: :recycle: Refactor

#61 ♻️ refactor: 방 시작하기 수정
  basterdz-api/src/main/java/com/dnd/api/domains/room/dto/RoomIdResponse.java
  basterdz-api/src/main/java/com/dnd/api/domains/room/service/RoomService.java
  basterdz-domain/src/main/java/com/dnd/domain/room/entity/Room.java
  basterdz-domain/src/main/resources/db-local.yml
Labels: :recycle: Refactor

#63 ✨ feat: fcm을 통한 커스텀 메시지 기능 구현
  .github/workflows/ci.yml
  .gitignore
  basterdz-api/build.gradle
  basterdz-api/src/main/java/com/dnd/api/common/config/WebMvcConfig.java
  basterdz-api/src/main/java/com/dnd/api/domains/booster/BoosterController.java
  basterdz-api/src/main/java/com/dnd/api/domains/booster/BoosterService.java
  basterdz-api/src/main/java/com/dnd/api/domains/booster/SendBoosterRequest.java
  basterdz-api/src/main/java/com/dnd/api/domains/room/controller/RoomApiPresentation.java
  basterdz-api/src/main/java/com/dnd/api/domains/room/controller/RoomController.java
  basterdz-api/src/main/resources/application.yml
  basterdz-api/src/test/resources/application.yml
  basterdz-domain/src/main/java/com/dnd/domain/member/entity/Member.java
  basterdz-domain/src/main/resources/db-test.yml
  basterdz-external/build.gradle
  basterdz-external/src/main/java/com/dnd/external/fcm/FcmConfig.java
  basterdz-external/src/main/java/com/dnd/external/fcm/FcmService.java
  basterdz-external/src/main/java/com/dnd/external/fcm/PushMessage.java
  basterdz-external/src/main/resources/firebase.yml
  basterdz-infra/build.gradle
  settings.gradle
Labels: ✨Feature
